<a href="https://colab.research.google.com/github/AlejandroVillazonG/ayudantias_MAT281/blob/main/ayudantias_2023/Ayud4_MAT281_pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><img src="https://matematica.usm.cl/wp-content/themes/dmatUSM/assets/img/logoDMAT2.png" title="Title text" width= 800 /></center>
<hr style="height:2px;border:none"/>
<h1 align='center'> Ayudantía 4: Combinando datos, librería Pandas</h1>

<H3 align='center'> MAT281 2023-2 </H3>

<H3 align='center'> Ayud. Alejandro Villazón G. </H3>
<hr style="height:2px;border:none"/>

¿Te imaginas como las grandes compañías o gobiernos almacenan sus datos?

No, no es en un excel gigante en un pendrive.

Es importante saber como modificar o crear valor a través de distintas tablas de datos, por lo que esta ayudantía se centrará en hacer esto, motivando a partir del uso de bases de datos relacionales.

## Base de Datos

Una __Base de Datos__ es un conjunto de datos almacenados en una computadora (generalmente un servidor, máquina virtual, etc.) y que poseen una estructura tal que sean de fácil acceso.

### Base de Datos Relacional

Es el tipo de base de datos más ampliamente utilizado, aunque existen otros tipos de bases de datos para fines específicos. Utiliza una estructura tal que es posible identificar y acceder a datos relacionados entre si. Generalmente una base de datos relacional está organizada en __tablas__.

Las tablas están conformadas de filas y columnas. Cada columna posee un nombre y tiene un tipo de dato específico, mientras que las filas son registros almacenados.

Por ejemplo, la siguiente tabla tiene tres columnas y cuatro registros. En particular, la columna ```age``` tiene tipo ```INTEGER``` y las otras dos tipo ```STRING```.

![Tabla 1](https://s3.amazonaws.com/codecademy-content/courses/sql-intensive/table.jpg)

__¿Este formato de datos te parece familar?__

### ¿Qué es SQL?

Sus siglas significan _Structured Query Language_ (Lenguaje de Consulta Estructurada) es un lenguaje de programación utilizado para comunicarse con datos almacenados en un Sistema de Gestión de Bases de Datos Relacionales (_Relational Database Management System_ o RDBMS). Posee una sintaxis muy similar al idioma inglés, con lo cual se hace relativamente fácil de escribir, leer e interpretar.

Hay distintos RDBMS entre los cuales la sintaxis de SQL difiere ligeramente. Los más populares son:

- SQLite
- MySQL / MariaDB
- PostgreSQL
- Oracle DB
- SQL Server

En una empresa de tecnología hay cargos especialmente destinados a todo lo que tenga que ver con bases de datos, por ejemplo: creación, mantención, actualización, obtención de datos, transformación, seguridad y un largo etc.

Los matemáticos en la industria suelen tener cargos como _Data Scientist_, _Data Analyst_, _Data Statistician_, _Data X_ (reemplace _X_ con algo _fancy_ tal de formar un cargo que quede bien en Linkedin), en donde lo importante es otorgar valor a estos datos. Por ende, lo mínimo que deben satisfacer es:

- Entendimiento casi total del modelo de datos (tablas, relaciones, tipos, etc.)
- Seleccionar datos a medida (_queries_).

In [1]:
import pandas as pd

### Concatenar

Imagina que tienes varias tablas con las mismas columnas y quieres unirlas en una grande. La función `concat` está diseñada para esta labor.

![concat](https://pandas.pydata.org/pandas-docs/stable/_images/merging_concat_basic.png)

In [2]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])


df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                   index=[4, 5, 6, 7])


df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                   index=[8, 9, 10, 11])

pd.concat([df1, df2, df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

Si los dataframes tienen distintas columnas no es impedimento para concatenarlas.

In [3]:
df4 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
                    'D': ['D2', 'D3', 'D6', 'D7'],
                    'F': ['F2', 'F3', 'F6', 'F7']},
                    index=[2, 3, 6, 7])

pd.concat([df1, df4], ignore_index= True)

     A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
4  NaN  B2  NaN  D2   F2
5  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

¿Quieres que se agreguen columnas dependiendo de los index que tienen cada dataframe?

![concat3](https://pandas.pydata.org/pandas-docs/stable/_images/merging_concat_axis1.png)

In [4]:
pd.concat([df1, df4], axis=1)

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

Por defecto la función `.concat()` concatena a lo largo del axis=0.

### Unir

En pandas es posible unir dos tablas sin la necesidad de iterar fila por fila. La funcionalidad la entrega el método `merge`.

Existen distintos tipos de unir datos. Los cuatro tipos de cruces más comunes:

- ```inner```: (_default_) Retorna aquellos registros donde los valores de columnas utilizadas para los cruces se encuentran en ambas tablas.
- ```left```: Retorna todos los registros de la tabla colocada a la izquierda, aunque no tengan correspondencia en la tabla de la derecha.
- ```right```: Retorna todos los registros de la tabla colocada a la derecha, aunque no tengan correspondencia en la tabla de la izquierda.
- ```outer```: Retorna todos los valores de ambas tablas, tengan correspondencia o no.

La siguiente imagen explica el resultado que se obtiene con los distintos tipos de cruces.

![Joins](https://dataschool.com/assets/images/how-to-teach-people-sql/sqlJoins/sqlJoins_7.png?w=662&h=361)
![Joins2](https://lukaseder.files.wordpress.com/2016/07/venn-join1.png?w=662&h=361)

Veamos otros _ejemplitos_

In [5]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})


right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                      'C': ['C0', 'C1', 'C2', 'C3'],
                      'D': ['D0', 'D1', 'D2', 'D3']})

display(left)

display(right)

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

__Left Merge__

In [6]:
pd.merge(left, right, how = 'left', on=['key1', 'key2'])

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

__Right Merge__

![right_merge](https://pandas.pydata.org/pandas-docs/stable/_images/merging_merge_on_key_right.png)

In [7]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

__Outer Merge__

![outer_merge](https://pandas.pydata.org/pandas-docs/stable/_images/merging_merge_on_key_outer.png)

In [8]:
pd.merge(left, right, how='outer', on=['key1', 'key2'])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

__Inner Merge__

![inner_merge](https://pandas.pydata.org/pandas-docs/stable/_images/merging_merge_on_key_inner.png)

In [9]:
pd.merge(left, right, on=['key1', 'key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

__Problemas de llaves duplicadas__

Cuando se quiere realizar el cruce de dos tablas, pero en ambas tablas existe una columna (key) con el mismo nombre, para diferenciar la información entre la columna de una tabla y otra, pandas devuelve el nombre de la columna con un guión bajo x (key_x) y otra con un guión bajo y (key_y)

In [10]:
left2 = pd.DataFrame({'A': [1, 2], 'B': [2, 2]})
right2 = pd.DataFrame({'A': [4, 5, 6], 'B': [2, 2, 2]})

display(left2)
display(right2)

pd.merge(left2, right2, on='B', how='outer')

   A  B
0  1  2
1  2  2

   A  B
0  4  2
1  5  2
2  6  2

   A_x  B  A_y
0    1  2    4
1    1  2    5
2    1  2    6
3    2  2    4
4    2  2    5
5    2  2    6

Tambien podemos cruzar todos los datos de ambas tablas.

In [11]:
left.merge(right, how = 'cross', suffixes= ['_left', '_right'])

   key1_left key2_left   A   B key1_right key2_right   C   D
0         K0        K0  A0  B0         K0         K0  C0  D0
1         K0        K0  A0  B0         K1         K0  C1  D1
2         K0        K0  A0  B0         K1         K0  C2  D2
3         K0        K0  A0  B0         K2         K0  C3  D3
4         K0        K1  A1  B1         K0         K0  C0  D0
5         K0        K1  A1  B1         K1         K0  C1  D1
6         K0        K1  A1  B1         K1         K0  C2  D2
7         K0        K1  A1  B1         K2         K0  C3  D3
8         K1        K0  A2  B2         K0         K0  C0  D0
9         K1        K0  A2  B2         K1         K0  C1  D1
10        K1        K0  A2  B2         K1         K0  C2  D2
11        K1        K0  A2  B2         K2         K0  C3  D3
12        K2        K1  A3  B3         K0         K0  C0  D0
13        K2        K1  A3  B3         K1         K0  C1  D1
14        K2        K1  A3  B3         K1         K0  C2  D2
15        K2        K1  A3  B3         K2         K0  C3  D3

No es necesario que la columna compartida tenga el mismo nombre!

In [12]:
left.merge(right, how = 'right', left_on = 'key2', right_on = 'key1', suffixes= ['_left', '_right'])

  key1_left key2_left    A    B key1_right key2_right   C   D
0        K0        K0   A0   B0         K0         K0  C0  D0
1        K1        K0   A2   B2         K0         K0  C0  D0
2        K0        K1   A1   B1         K1         K0  C1  D1
3        K2        K1   A3   B3         K1         K0  C1  D1
4        K0        K1   A1   B1         K1         K0  C2  D2
5        K2        K1   A3   B3         K1         K0  C2  D2
6       NaN       NaN  NaN  NaN         K2         K0  C3  D3

Considera que `merge` también se puede usar como método, por lo que es posible concatener varias operaciones.

## Ejercicios

Continuemos trabajando con nuestro dataset de partidos.

In [13]:
matches = pd.read_csv(
    'https://raw.githubusercontent.com/footballcsv/england/master/2020s/2020-21/eng.1.csv'
)
matches

     Round             Date          Team 1   FT          Team 2
0        1  Sat Sep 12 2020          Fulham  0–3         Arsenal
1        1  Sat Sep 12 2020  Crystal Palace  1–0     Southampton
2        1  Sat Sep 12 2020       Liverpool  4–3    Leeds United
3        1  Sat Sep 12 2020        West Ham  0–2   Newcastle Utd
4        1  Sun Sep 13 2020       West Brom  0–3  Leicester City
..     ...              ...             ...  ...             ...
375     38  Sun May 23 2021        West Ham  3–0     Southampton
376     38  Sun May 23 2021    Leeds United  3–1       West Brom
377     38  Sun May 23 2021         Arsenal  2–0        Brighton
378     38  Sun May 23 2021       Liverpool  2–0  Crystal Palace
379     38  Sun May 23 2021          Fulham  0–2   Newcastle Utd

[380 rows x 5 columns]

### 1. Invierte la localía de cada partido y su resultado para crear un DataFrame alargado. Es decir, dentro de los registros cada partido debe aparecer dos veces. Por ejemplo,
### Fulham 0-3 Arsenal
### Arsenal 3-0 Fulham
El DataFrame resultante debe tener 760 filas y 5 columnas.

**HINT:** Podría ser útil la ``pd.concat()`` con el DataFrame original y otro invertido.

In [17]:
# ESCRIBE TU CODE AQUÍ

     Round             Date          Team 1   FT          Team 2
0        1  Sat Sep 12 2020          Fulham  0–3         Arsenal
1        1  Sat Sep 12 2020  Crystal Palace  1–0     Southampton
2        1  Sat Sep 12 2020       Liverpool  4–3    Leeds United
3        1  Sat Sep 12 2020        West Ham  0–2   Newcastle Utd
4        1  Sun Sep 13 2020       West Brom  0–3  Leicester City
..     ...              ...             ...  ...             ...
375     38  Sun May 23 2021     Southampton  0–3        West Ham
376     38  Sun May 23 2021       West Brom  1–3    Leeds United
377     38  Sun May 23 2021        Brighton  0–2         Arsenal
378     38  Sun May 23 2021  Crystal Palace  0–2       Liverpool
379     38  Sun May 23 2021   Newcastle Utd  2–0          Fulham

[760 rows x 5 columns]

### 2. En una temporada dos clubes se enfrentan dos veces. Por ejemplo, el primer partido fue un Fulham vs Arsenal, entonces dentro de los registros hay un Arsenal vs Fulham. Queremos analizar los resultados de ida y vuelta para esto crea un DataFrame donde cada fila nos entregue el partido de ida y vuelta, ambos junto a su información.

No dupliques información, el DataFrame debe tener 190 filas.

**HINT:** Usa la función `pd.merge()` con los argumentos apropiados.

In [18]:
# ESCRIBE TU CODE AQUÍ

,Round_ida,Date_ida,Team 1_ida,FT_ida,Team 2_ida,Round_vuelta,Date_vuelta,Team 1_vuelta,FT_vuelta,Team 2_vuelta
0,1,Sat Sep 12 2020,Fulham,0–3,Arsenal,32,Sun Apr 18 2021,Arsenal,1–1,Fulham
1,1,Sat Sep 12 2020,Crystal Palace,1–0,Southampton,32,Tue May 11 2021(P),Southampton,3–1,Crystal Palace
2,1,Sat Sep 12 2020,Liverpool,4–3,Leeds United,32,Mon Apr 19 2021,Leeds United,1–1,Liverpool
3,1,Sat Sep 12 2020,West Ham,0–2,Newcastle Utd,32,Sat Apr 17 2021,Newcastle Utd,3–2,West Ham
4,1,Sun Sep 13 2020,West Brom,0–3,Leicester City,32,Thu Apr 22 2021,Leicester City,3–0,West Brom
...,...,...,...,...,...,...,...,...,...,...
185,19,Sun Jan 17 2021,Sheffield Utd,1–3,Tottenham,34,Sun May 02 2021,Tottenham,4–0,Sheffield Utd
186,19,Sun Jan 17 2021,Liverpool,0–0,Manchester Utd,34,Thu May 13 2021(P),Manchester Utd,2–4,Liverpool
187,19,Sun Jan 17 2021,Manchester City,4–0,Crystal Palace,34,Sat May 01 2021,Crystal Palace,0–2,Manchester City
188,19,Mon Jan 18 2021,Arsenal,3–0,Newcastle Utd,34,Sun May 02 2021,Newcastle Utd,0–2,Arsenal
189,19,Thu May 13 2021(P),Aston Villa,0–0,Everton,34,Sat May 01 2021,Everton,1–2,Aston Villa